### ISSUE TITLE
Request: Presidential Seal of Approval

### ISSUE THREAD

**Issue by stephengfriend** [rgbkrk/obama#1]
Can we get an actual presidential seal of approval badge?

https://backpacksandbabygrows.files.wordpress.com/2014/08/approved.png
http://www.theuspresidents.org/wp-content/uploads/2015/04/Presidential_Seal_TheUSPresidents.jpg

**Comment by rgbkrk** [comment]
A riff on

![](http://www.theuspresidents.org/wp-content/uploads/2015/04/Presidential_Seal_TheUSPresidents.jpg)

would be so excellent.

**Comment by stephengfriend** [comment]
I'm bad at pixels or I'd tackle it myself.

**Comment by konsumer** [comment]
[here](https://raw.githubusercontent.com/konsumer/obama/master/seal.ans) is the ANSI for that.
